### ISSUE TITLE
Make conda forge, currently failing

### ISSUE THREAD

**Issue by knc6** [usnistgov/tb3py#13]
https://github.com/conda-forge/staged-recipes/pull/25920
Add meta.yaml
```
{% set name = "tb3py" %}
{% set version = "2024.3.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/tb3py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5769fcdb1a2ca941010d2a9e1a8684ff23749456d6962e27f980fd2ced3ec62

build:
  number: 0
  script:
    - echo 'Getting julia'
    - apt-get update && apt-get install -y wget  # [linux]
    - wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.3-linux-x86_64.tar.gz  # [linux]
    - tar -xzf julia-1.6.3-linux-x86_64.tar.gz  # [linux]
    - export PATH=$PWD/julia-1.6.3/bin:$PATH  # [linux]
    - "{{ PYTHON }} -m pip install . -vv"



requirements:
  host:
    - pip
    - python >=3.8
    - julia >=1.10.2
    - requests >=2.26.0
    - setuptools
  run:
    - jarvis-tools
    - julia >=1.10.2
    - numpy >=1.19.5
    - pytest
    - python >=3.6
    - requests >=2.26.0

test:
  imports:
    - tb3py
    - tb3py.tests


about:
  home: https://github.com/usnistgov/tb3py
  summary: 'tb3: an open-source software package for accurate and efficient electronic structure calculations using tight-binding (TB), including three-body interactions. https://pages.nist.gov/ThreeBodyTB.jl'
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
```
